version: 1
services:
  - type: web
    name: my-puppeteer-app # Replace with your app name
    env: node
    plan: free
    buildCommand: |
      echo "Updating package list..."
      apt-get update
      echo "Installing necessary packages..."
      apt-get install -y libnss3 libx11-xcb1 libxcomposite1 fonts-liberation
      echo "Installing Puppeteer browsers..."
      npx puppeteer browsers install chrome || { echo 'Puppeteer browser install failed'; exit 1; }
      echo "Contents of Puppeteer cache directory:"
      ls -la /opt/render/.cache/puppeteer/chrome/ || { echo 'Failed to list Puppeteer cache directory'; exit 1; }
      echo "Installing Node dependencies..."
      npm install || { echo 'Node dependencies install failed'; exit 1; }
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
      - key: CHROMIUM_PATH
        value: "/opt/render/.cache/puppeteer/chrome/linux-*/*/chrome" # Use wildcard for dynamic path
