# This file configures the Render service for your Puppeteer app
version: 1
services:
  - type: web
    name: my-puppeteer-app # Replace with your app name
    env: node
    plan: free # Choose your plan (free, starter, etc.)
    buildCommand: npm install
    startCommand: node src/index.js # Replace with your entry point
    envVars:
      - key: CHROMIUM_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-129.0.6668.89/chrome-linux/chrome # Set the correct path to Chromium
    prebuildCommand: npx puppeteer browsers install chrome # Install Chromium before the build starts
