version: 1
services:
  - type: web
    name: my-puppeteer-app # Replace with your app name
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y libnss3 libx11-xcb1 libxcomposite1 fonts-liberation
      npx puppeteer browsers install chrome
      npm install
    startCommand: npm start # Using npm start for flexibility
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
      - key: CHROMIUM_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-129.0.6668.89/chrome-linux/chrome
